apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ddadekunle/Hybrid_Serverless_Container_AWS
    targetRevision: main
    path: services/api/helm
    helm:
      values: |
        image:
          repository: 499266301413.dkr.ecr.eu-west-1.amazonaws.com/hybrid-capstone-api
          tag: "0.1.4"
        service:
          type: ClusterIP
          port: 80
        ingress:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
